### ISSUE TITLE
Videos can be created without some mandatory data

### ISSUE THREAD

**Issue by acotiuga** [apivideo/java-sdk#1]
Hello java-sdk developers,

I have issues when I'm trying to get a list of all videos. It looks like the `publishedAt` is `null` in some of them and that makes the `VideoClient#list()` method call to fail. I was expecting `publishedAt` to be anything but `null` since it represents the date of the video upload. Am I missing something? Here's my stacktrace, hope it helps:
```
Caused by: org.json.JSONException: JSONObject["publishedAt"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:721)
	at video.api.java.sdk.infrastructure.unirest.video.VideoDeserializer.deserialize(VideoDeserializer.java:13)
	at video.api.java.sdk.infrastructure.unirest.video.VideoDeserializer.deserialize(VideoDeserializer.java:8)
	at video.api.java.sdk.infrastructure.unirest.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:19)
	at video.api.java.sdk.infrastructure.pagination.PageDeserializer.deserialize(PageDeserializer.java:26)
	at video.api.java.sdk.infrastructure.unirest.pagination.UriPageLoader.load(UriPageLoader.java:31)
	at video.api.java.sdk.infrastructure.pagination.PageIterator.loadPage(PageIterator.java:47)
	at video.api.java.sdk.infrastructure.pagination.PageIterator.hasNext(PageIterator.java:30)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:394)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:207)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:342)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluateInternal(DefaultVelocityEngine.java:259)
	at org.xwiki.velocity.internal.DefaultVelocityEngine.evaluate(DefaultVelocityEngine.java:222)
```

Thanks,
Alex

**Comment by apiv-thomas** [comment]
Hello Alex, 
I will have a look at this issue today and get back to you.

**Comment by apiv-thomas** [comment]
We found a few cases where the `publishedAt` attribute was null in the response.
It should be fixed now. Can you try again?

**Comment by acotiuga** [comment]
It was fixed, indeed. Thank you!
